path: ./data/object_data
train: train/images
val:   val/images
test:  test/images
nc: 11
names:
  0: vehicle
  1: bike
  2: traffic_light_red
  3: traffic_light_green
  4: traffic_light_yellow
  5: traffic_light_off
  6: speed_sign_30
  7: speed_sign_60
  8: speed_sign_90
  9: traffic_sign
  10: pedestrian